# Preload is still required
preload = /home/michal/.config/hypr/wallpapers/cyberpunk1.jpg
preload = /home/michal/.config/hypr/wallpapers/cyberpunk3.png

# New block syntax for monitors
wallpaper {
    monitor = DP-1
    path = /home/michal/.config/hypr/wallpapers/cyberpunk3.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/michal/.config/hypr/wallpapers/cyberpunk1.jpg
    fit_mode = cover
}

# Optional settings
splash = false
ipc = on
